export default function PrivacyPage() {
  return (
    <main style={{ maxWidth: 760, margin: "48px auto", padding: "0 20px 60px", fontFamily: "Arial, sans-serif", lineHeight: 1.7 }}>
      <h1>VAELONS Etsy Manager Privacy</h1>
      <p>
        VAELONS Etsy Manager connects an authorized Etsy shop to schedule draft listings for future publication.
      </p>
      <p>
        The service uses Etsy authorization tokens only to identify the connected shop, read draft listings, and publish drafts at times explicitly scheduled by the authorized user. It does not sell personal data and does not use Etsy credentials for advertising.
      </p>
      <p>
        GPT Action access uses an encrypted bearer key generated by the authenticated Manager session. The key should be kept private and used only in the GPT Action authentication settings.
      </p>
      <p>
        The GPT Action API is limited to listing current drafts and scheduling drafts for publication. It does not edit listing titles, descriptions, tags, prices, images, stock, shipping settings, or variations.
      </p>
      <p>Contact: vaelons.official@gmail.com</p>
    </main>
  );
}
