"use client";
import {useState} from "react";
const presets=[["floor_large","Yerde Büyük — tek thumbnail"],["wall_large","Duvarda Büyük — tek thumbnail"]];
export default function ThumbnailEnginePanel(){
 const[data,setData]=useState(null),[busy,setBusy]=useState(false),[err,setErr]=useState(""),[job,setJob]=useState(null),[preset,setPreset]=useState("floor_large");
 async function call(body){const r=await fetch("/api/etsy/thumbnail-engine",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||"İşlem başarısız");return j}
 async function scan(){setBusy(true);setErr("");try{setData(await call({action:"scan",listingLimit:500}))}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function prepare(x){setBusy(true);setErr("");try{const j=await call({action:"source",listingId:x.listing_id});setJob({listing_id:x.listing_id,preset,source_locked:true,source_artwork:j.source_artwork||j.artwork||x.source_artwork,title:x.title,local_renderer:true})}catch(e){setErr(e.message)}finally{setBusy(false)}}
 return <main style={shell}><section style={hero}><div style={eyebrow}>VAELONS · ZERO-COST CREATIVE ENGINE</div><h1 style={{fontSize:"clamp(30px,5vw,44px)",margin:"7px 0"}}>Creative Studio</h1><p style={{color:"#cbd5e1",maxWidth:760,lineHeight:1.6}}>Dış görsel API'si yok. Rank‑1 artwork aynen korunur ve tarayıcı içinde ücretsiz premium mockup olarak sunulur.</p></section>
 <div style={toolbar}><button onClick={scan} disabled={busy} style={btn}>{busy?"İşleniyor…":"Tüm Aktif Listingleri Tara"}</button><select value={preset} onChange={e=>setPreset(e.target.value)} style={select}>{presets.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></div>
 {err&&<p style={{color:"#991b1b",fontWeight:700}}>{err}</p>}
 {job&&<Workspace job={job} close={()=>setJob(null)}/>}
 {data&&<><div style={metrics}><M n={data.total_count} t="Aktif"/><M n={data.needs_change_count} t="Değişmeli"/><M n={data.review_count} t="İncele"/><M n={data.strong_count} t="Güçlü"/></div><div style={{display:"grid",gap:10}}>{(data.results||[]).map(x=><div key={x.listing_id} style={card}>{x.source_artwork?.url&&<img src={x.source_artwork.url} alt="" style={thumb}/>}<div style={{flex:1,minWidth:0}}><b>{x.title}</b><div style={meta}>Listing {x.listing_id} · {x.image_count||0} görsel · Rank‑1 kilit: {x.source_locked?"Evet":"Hayır"}</div><div style={{marginTop:6}}>Thumbnail skoru: <b>{x.thumbnail_score}/100</b> · {x.status}</div></div><button style={btn2} disabled={busy||!x.source_locked} onClick={()=>prepare(x)}>1 Thumbnail Hazırla</button></div>)}</div></>}
 </main>
}
function Workspace({job,close}){const src=job.source_artwork?.url;const wall=job.preset==="wall_large";return <section style={panel}><div style={eyebrowDark}>ÜCRETSİZ YEREL RENDER · ARTWORK LOCKED</div><h2 style={{margin:"6px 0 12px"}}>Listing {job.listing_id}</h2><div style={scene}>
 <div style={wall?wallArt:floorArt}>{src?<img src={src} alt="Locked source artwork" style={artImg}/>:<div style={{padding:20}}>Rank‑1 artwork alınamadı.</div>}</div>
 <div style={floorLine}/><div style={sofa}/><div style={sideTable}/><div style={vase}/>
 </div><div style={ok}>✓ Artwork yeniden çizilmedi · ✓ Crop/stretch yok · ✓ Dış API maliyeti yok · ✓ Tek hero thumbnail</div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:12}}><button style={btn2} onClick={close}>Çalışma alanını kapat</button></div></section>}
function M({n,t}){return <div style={metric}><b style={{fontSize:24}}>{n}</b><div style={{fontSize:12}}>{t}</div></div>}
const shell={maxWidth:1180,margin:"24px auto 64px",padding:"0 18px",fontFamily:"Inter,ui-sans-serif,system-ui,-apple-system,sans-serif",color:"#0f172a"},hero={padding:28,borderRadius:22,background:"linear-gradient(135deg,#07111f,#172033)",color:"#fff",marginBottom:18,boxShadow:"0 22px 55px rgba(15,23,42,.18)"},eyebrow={fontSize:11,fontWeight:900,letterSpacing:"1.5px",color:"#94a3b8"},eyebrowDark={fontSize:11,fontWeight:900,letterSpacing:"1.2px",color:"#64748b"},toolbar={display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"},btn={padding:"12px 16px",border:0,borderRadius:9,background:"#111827",color:"#fff",fontWeight:800,cursor:"pointer"},btn2={...btn,background:"#fff",color:"#111827",border:"1px solid #cbd5e1"},select={padding:11,border:"1px solid #cbd5e1",borderRadius:9},metrics={display:"flex",gap:10,flexWrap:"wrap",margin:"16px 0"},metric={padding:14,background:"#fff",border:"1px solid #e2e8f0",borderRadius:14,boxShadow:"0 6px 20px rgba(15,23,42,.04)"},card={display:"flex",gap:14,alignItems:"center",background:"#fff",border:"1px solid #e2e8f0",borderRadius:14,padding:12,flexWrap:"wrap"},thumb={width:110,height:90,objectFit:"contain",background:"#eee",borderRadius:8},meta={fontSize:12,color:"#64748b",marginTop:4},panel={marginTop:18,padding:18,background:"#fff",border:"2px solid #111827",borderRadius:18,boxShadow:"0 24px 60px rgba(15,23,42,.14)"},scene={height:"min(64vw,620px)",minHeight:360,position:"relative",overflow:"hidden",borderRadius:16,background:"linear-gradient(#e9e3da 0 72%,#c8b9a5 72% 100%)",marginTop:12},floorLine={position:"absolute",left:0,right:0,top:"72%",height:2,background:"rgba(80,65,50,.18)"},wallArt={position:"absolute",left:"50%",top:"9%",transform:"translateX(-50%)",width:"46%",height:"54%",background:"#fff",boxShadow:"0 18px 45px rgba(0,0,0,.25)",padding:0},floorArt={position:"absolute",left:"12%",bottom:"7%",width:"42%",height:"64%",background:"#fff",boxShadow:"12px 20px 35px rgba(0,0,0,.28)",transform:"rotate(-1deg)",zIndex:3},artImg={width:"100%",height:"100%",objectFit:"contain",display:"block",background:"#111"},sofa={position:"absolute",right:"5%",bottom:"4%",width:"43%",height:"20%",background:"#b4a898",borderRadius:"34px 34px 8px 8px",boxShadow:"0 16px 24px rgba(0,0,0,.15)"},sideTable={position:"absolute",right:"3%",bottom:"4%",width:"10%",height:"15%",background:"#7f6752",borderRadius:"50% 50% 8px 8px"},vase={position:"absolute",right:"6%",bottom:"18%",width:"4%",height:"9%",background:"#eee7db",borderRadius:"45% 45% 35% 35%"},ok={padding:12,background:"#ecfdf5",border:"1px solid #a7f3d0",borderRadius:10,color:"#065f46",marginTop:12,fontWeight:700};
