"use client";import{useState}from"react";
const presets=[["floor_large","Yerde Büyük"],["wall_large","Duvarda Büyük"],["living_room","Salon"],["bedroom","Yatak Odası"],["detail","Detay"],["scale","Ölçek"]];
export default function ThumbnailEnginePanel(){const[data,setData]=useState(null),[busy,setBusy]=useState(false),[err,setErr]=useState(""),[job,setJob]=useState(null),[preset,setPreset]=useState("floor_large");
async function call(body){const r=await fetch("/api/etsy/thumbnail-engine",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||"İşlem başarısız");return j}
async function scan(){setBusy(true);setErr("");try{setData(await call({action:"scan",listingLimit:500}))}catch(e){setErr(e.message)}finally{setBusy(false)}}
async function prepare(x){setBusy(true);setErr("");try{setJob(await call({action:"prepare",listingId:x.listing_id,preset}))}catch(e){setErr(e.message)}finally{setBusy(false)}}
return <main style={{maxWidth:1100,margin:"32px auto",padding:"0 20px",fontFamily:"Arial"}}><h1>VAELONS Thumbnail Manager</h1><p>Tüm aktif listingleri tarar. Rank‑1 artwork kaynak kilididir; artwork değiştirilmeden mockup hazırlama akışına gönderilir.</p><div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}><button onClick={scan} disabled={busy} style={btn}>{busy?"İşleniyor…":"Tüm Aktif Listingleri Tara"}</button><select value={preset} onChange={e=>setPreset(e.target.value)} style={select}>{presets.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></div>{err&&<p style={{color:"#991b1b"}}>{err}</p>}{data&&<><div style={{display:"flex",gap:10,flexWrap:"wrap",margin:"16px 0"}}><M n={data.total_count} t="Aktif"/><M n={data.needs_change_count} t="Değişmeli"/><M n={data.review_count} t="İncele"/><M n={data.strong_count} t="Güçlü"/></div><div style={{display:"grid",gap:10}}>{data.results.map(x=><div key={x.listing_id} style={card}>{x.source_artwork?.url&&<img src={x.source_artwork.url} alt="" style={{width:110,height:90,objectFit:"contain",background:"#eee",borderRadius:8}}/>}<div style={{flex:1}}><b>{x.title}</b><div style={{fontSize:12,color:"#666"}}>Listing {x.listing_id} · {x.image_count||0} görsel · Rank‑1 kilit: {x.source_locked?"Evet":"Hayır"}</div><div style={{marginTop:6}}>Thumbnail skoru: <b>{x.thumbnail_score}/100</b> · {x.status}</div>{x.issues?.length>0&&<div style={{fontSize:12,color:"#9a3412"}}>{x.issues.join(" · ")}</div>}</div><button style={btn2} disabled={busy||!x.source_locked} onClick={()=>prepare(x)}>Geliştir / Hazırla</button></div>)}</div></>}
{job&&<section style={panel}><h2>Thumbnail işi hazırlandı</h2><p><b>Listing:</b> {job.listing_id} · <b>Preset:</b> {job.preset}</p>{job.source_artwork?.url&&<img src={job.source_artwork.url} alt="" style={{maxWidth:260,maxHeight:220,objectFit:"contain"}}/>}<p>Artwork kilidi: <b>{job.source_locked?"Açık":"Kapalı"}</b>. Yeniden çizme, recolor, crop ve stretch yasak.</p>{job.provider_connected===false&&<div style={warn}>Görsel üretim sağlayıcısı henüz bağlı değil. Bu nedenle sistem Etsy’ye uydurma görsel yüklemiyor. Üretim sağlayıcısı bağlandığında burada “10 Thumbnail Üret → Önizle → Seç → Etsy’ye Uygula” adımları açılacak.</div>}<button style={btn2} onClick={()=>setJob(null)}>Kapat</button></section>}</main>}
function M({n,t}){return <div style={{padding:12,background:"#fff",border:"1px solid #ddd",borderRadius:10}}><b style={{fontSize:24}}>{n}</b><div style={{fontSize:12}}>{t}</div></div>}const btn={padding:"12px 16px",border:0,borderRadius:9,background:"#111827",color:"#fff",fontWeight:800,cursor:"pointer"};const btn2={...btn,background:"#fff",color:"#111827",border:"1px solid #ccc"};const select={padding:11,border:"1px solid #ccc",borderRadius:9};const card={display:"flex",gap:14,alignItems:"center",background:"#fff",border:"1px solid #ddd",borderRadius:12,padding:12};const panel={marginTop:18,padding:18,background:"#fff",border:"2px solid #111827",borderRadius:14};const warn={padding:12,background:"#fffbeb",border:"1px solid #fcd34d",borderRadius:9,color:"#92400e",margin:"12px 0"};
